package plg_caption

import (
	"bytes"
	"encoding/json"
	_ "embed"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/gorilla/mux"
	. "github.com/mickael-kerjean/filestash/server/common"
)

//go:embed caption-plugin.js
var captionPluginJS []byte

const (
	// outputClipDir is the directory where caption sidecar JSON files are written.
	// Must match the /srv/output_clip mount in docker-compose.yml.
	outputClipDir = "/srv/output_clip"

	// dashboardCaptionURL is the dashboard endpoint that publishes to Kafka.
	// Resolved via Docker DNS inside the compose network.
	dashboardCaptionURL = "http://dashboard:3000/api/caption"
)

func init() {
	// Serve the embedded JS at a known URL.
	Hooks.Register.HttpEndpoint(func(r *mux.Router) error {
		r.HandleFunc("/api/plugin/caption/plugin.js", servePluginJS).Methods("GET")
		r.HandleFunc("/api/plugin/caption", handleCaption).Methods("POST")
		return nil
	})

	// Tell the Filestash frontend to load our JS on every page.
	Hooks.Register.FrontendOverrides("/api/plugin/caption/plugin.js")

	// Register the metadata provider so captions appear in the info panel.
	Hooks.Register.Metadata(CaptionMetadata{})
}

// ── Static JS handler ──────────────────────────────────────────────────────────

func servePluginJS(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/javascript; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Write(captionPluginJS)
}

// ── Caption API handler ────────────────────────────────────────────────────────
//
// Forwards the caption request from the browser to the dashboard, which
// publishes it to Kafka. This keeps the Kafka broker unreachable from the
// browser and lets the proxy layer remain simple.

type captionRequest struct {
	JobID     string `json:"job_id"`
	ImagePath string `json:"image_path"`
}

func handleCaption(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	if err != nil {
		http.Error(w, `{"error":"read error"}`, http.StatusBadRequest)
		return
	}

	var req captionRequest
	if err := json.Unmarshal(body, &req); err != nil || req.ImagePath == "" {
		http.Error(w, `{"error":"invalid request"}`, http.StatusBadRequest)
		return
	}

	resp, err := http.Post(dashboardCaptionURL, "application/json", bytes.NewReader(body))
	if err != nil {
		http.Error(w, `{"error":"dashboard unavailable"}`, http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(resp.StatusCode)
	io.Copy(w, resp.Body)
}

// ── IMetadata implementation ───────────────────────────────────────────────────

// CaptionMetadata reads caption sidecar JSON files written by the captioner.
type CaptionMetadata struct{}

// captionFile is the structure written by the captioner next to its output.
type captionFile struct {
	JobID     string `json:"job_id"`
	ImagePath string `json:"image_path"`
	Caption   string `json:"caption"`
	Timestamp string `json:"timestamp"`
}

// Get returns the caption for the given Filestash path, or an empty slice if
// no caption has been generated yet.
//
// path looks like "/images/subdir/photo.png".
// Sidecar file is at /srv/output_clip/subdir/photo.json.
func (CaptionMetadata) Get(ctx *App, path string) ([]FormElement, error) {
	sidecarPath := sidecarPathFor(path)
	if sidecarPath == "" {
		return nil, nil
	}

	data, err := os.ReadFile(sidecarPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("caption: read sidecar: %w", err)
	}

	var cf captionFile
	if err := json.Unmarshal(data, &cf); err != nil || cf.Caption == "" {
		return nil, nil
	}

	return []FormElement{
		{
			Name:     "Caption",
			Type:     "long_text",
			Value:    cf.Caption,
			ReadOnly: true,
		},
	}, nil
}

// Set is a no-op — captions are generated by the captioner, not edited here.
func (CaptionMetadata) Set(ctx *App, path string, value []FormElement) error {
	return nil
}

// Search is not implemented.
func (CaptionMetadata) Search(ctx *App, path string, facets map[string]any) (map[string][]FormElement, error) {
	return nil, nil
}

// ── Helpers ────────────────────────────────────────────────────────────────────

// sidecarPathFor converts a Filestash data-path to the sidecar JSON path.
//
//   /images/subdir/photo.png  →  /srv/output_clip/subdir/photo.json
//   /output_clip/subdir/x.mp4 →  "" (non-image prefixes are ignored)
func sidecarPathFor(filePath string) string {
	rel := strings.TrimPrefix(filePath, "/images/")
	if rel == filePath {
		// Path didn't start with /images/ — not an input image, skip.
		return ""
	}
	// Replace extension with .json
	ext := filepath.Ext(rel)
	if ext != "" {
		rel = rel[:len(rel)-len(ext)]
	}
	rel += ".json"
	return filepath.Join(outputClipDir, rel)
}
